#documents
documents = [
    
    {"name": "LeavePolicy.txt", "content": "Employees are entitled to 20 days of paid leave annually. Leave requests should be submitted at least two weeks in advance through the HR portal. Unused leave may be carried over to the next year up to a maximum of 5 days. Special leave, such as bereavement or parental leave, is available upon request and subject to approval."},
    {"name": "WorkFromHomePolicy.txt", "content": "Employees may work from home up to 3 days a week, provided their duties allow for remote work. Approval from the line manager is required. Employees must ensure a productive work environment and be available during core business hours. All company data accessed remotely must be handled securely."},
    {"name": "CodeOfConduct.txt", "content": "All employees must adhere to respectful communication, maintain professionalism, and foster an inclusive workplace. Discrimination, harassment, or any form of misconduct will not be tolerated. Employees are expected to report any violations to HR or their supervisor promptly."},
    {"name": "ITPolicy.txt", "content": "Company devices must be secured and used for work only. Employees are responsible for updating software regularly and reporting any security incidents immediately. Personal use of company devices should be minimal and must not interfere with work responsibilities."},
    {"name": "Benefits.txt", "content": "Health insurance, dental coverage, and gym reimbursement are provided to all full-time employees. Additional benefits include mental health support, paid parental leave, and access to wellness programs. Details of each benefit can be found in the employee handbook or by contacting HR."},
    {"name": "ProbationPeriod.txt", "content": "New hires undergo a 3-month probation period during which their performance and cultural fit are evaluated. Feedback will be provided regularly, and successful completion of probation will be confirmed in writing. Extensions to the probation period may be considered if necessary."},
    {"name": "TravelPolicy.txt", "content": "Business travel must be pre-approved by the line manager. Employees should book travel through the company's preferred vendors and adhere to the travel expense guidelines. All receipts must be submitted within 7 days of return for reimbursement."},
    {"name": "PerformanceReview.txt", "content": "Performance is reviewed bi-annually based on KPIs and individual goals. Employees are encouraged to participate actively in the review process and set development objectives. Constructive feedback will be provided, and training opportunities may be recommended."},
    {"name": "ExitPolicy.txt", "content": "Resignation requires a 30-day notice period, submitted in writing to the supervisor and HR. An exit interview will be conducted to gather feedback. All company property must be returned before the final day of employment, and outstanding expenses must be settled."},
    {"name": "OnboardingGuide.txt", "content": "New employees must complete orientation within the first week, which includes training on company policies, IT systems, and team introductions. A mentor will be assigned to assist with the transition. All required documentation must be submitted to HR during this period."},
    {"name": "DressCode.txt", "content": "Employees are expected to dress in business casual attire during office hours. Exceptions may be made for fieldwork or special events. Casual Fridays allow for more relaxed dress, but clothing should remain professional and appropriate for the workplace."},
    {"name": "RemoteWorkGuidelines.txt", "content": "Remote work requires stable internet and availability during core hours. Employees must attend virtual meetings and respond to communications promptly. The company may provide equipment as needed, and all remote work arrangements must be reviewed annually."},
    {"name": "ExpensePolicy.txt", "content": "All expenses must be submitted with receipts within 30 days of incurring the cost. Only business-related expenses are eligible for reimbursement. The finance team reviews all claims, and any discrepancies will be communicated to the employee for clarification."},
    {"name": "DataPrivacy.txt", "content": "Personal data must be handled in accordance with GDPR regulations. Employees are responsible for safeguarding confidential information and reporting any data breaches immediately. Regular training on data privacy is mandatory for all staff."},
    {"name": "MeetingEtiquette.txt", "content": "Meetings should start on time and have a clear agenda circulated in advance. Participants are expected to contribute constructively and respect others’ viewpoints. Action items and minutes should be documented and shared after each meeting."},
    {"name": "SecurityPolicy.txt", "content": "Passwords must be updated every 90 days and not shared with anyone. Employees should lock their computers when away from their desks and report suspicious activity to IT. Regular security awareness training is provided to all staff."},
    {"name": "EqualOpportunity.txt", "content": "The company is committed to providing equal opportunities for all employees regardless of race, gender, age, religion, or disability. Recruitment, promotion, and training decisions are based on merit and business needs. Any concerns should be reported to HR."},
    {"name": "HarassmentPolicy.txt", "content": "Harassment of any kind will not be tolerated and should be reported immediately to HR or a supervisor. All complaints will be investigated promptly and confidentially. Support resources are available for affected employees."},
    {"name": "TrainingAndDevelopment.txt", "content": "Employees are encouraged to attend at least one training session per quarter to enhance their skills. The company offers a variety of internal and external training programs. Requests for additional training can be submitted to the HR department."},
    {"name": "InternetUsage.txt", "content": "Internet access is provided for work purposes; personal browsing should be limited and must not interfere with job responsibilities. Accessing inappropriate or illegal content is strictly prohibited and may result in disciplinary action."},
]
